version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    networks:
      - testdb
    volumes:
      - ./:/backend
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
  frontend:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASES: todos
      MYSQL_ROOT_PASSWORD: secret
    volumes:
      - ./todo-mysql-data/data:/var/lib/mysql
    networks:
      - testdb

networks:
  testdb:

volumes:
  todo-mysql-data:
